### ISSUE TITLE
The app does nothing

### ISSUE THREAD

**Issue by anaumchev** [TheElderMindseeker/IUEiffelReporter#1]
The app still displays the "Hello Eiffel Web World!" message

**Comment by Voisvet** [comment]
The main part of work is going in other branches like test_backend_database or frontend. They`ll be merged with master only when they are ready for using or open testing.

**Comment by anaumchev** [comment]
Be sure to have enough time for merging, because it may be very complicated given the number of branches.

**Comment by Voisvet** [comment]
Thank you for comments! IU Eiffel Reporter alpha v0.1.0 has been released. So, you can test and use it.
